project:
  render: 
    - supplement.qmd
  type: website
  output-dir: docs

author: 
  - name: Kristoffer Magnusson
    orcid: 0000-0003-0713-0556
    email: kristoffer.magnusson@ki.se
    url: https://rpsychologist.com
    affiliations:
      - name: Centre for Psychiatry Research, Department of Clinical Neuroscience, Karolinska Institutet, & Stockholm Health Care Services, Region Stockholm

code-tools: 
    source: https://github.com/rpsychologist/causal-therapist-effects-paper/blob/main/supplement.qmd

format:
    html: 
        output-file: index.html
    pdf: 
        output-file: magnusson-2023-causal-therapist-effects.pdf